name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo(clone the repo)
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image (build and push to docker hub)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: jatin123lodhi/brainly-fe:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull jatin123lodhi/brainly-fe:latest  # Replace with your Docker Hub username and repository
    
    - name: Test Connectivity
      run: |
        ping -c 4 15.206.164.208
        nc -zv 15.206.164.208 22

    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull jatin123lodhi/brainly-fe:latest
          sudo docker stop brainly-fe || true
          sudo docker rm brainly-fe || true
          sudo docker run -d --name brainly-fe -p 3005:3000 jatin123lodhi/brainly-fe:latest