name: Test EC2 Connection

on:
  push:
    branches: [ master ]  # or master, depending on your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'echo "Connection successful!"'